stages:
  - compile-pdf
  - deploy

compile-pdf:
  stage: compile-pdf
  image: aergus/latex
  script:
    - cd dokumentacija
    - latexmk -pdf PROGI_2020_Ferllowship.tex
  artifacts:
    paths:
      - dokumentacija/PROGI_2020_Ferllowship.pdf
  only:
    - devdoc
    - /^doc/.*$/

deploy-frontend:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd frontend
    - dpl --provider=heroku --app=$HEROKU_FRONTEND --api-key=$HEROKU_API_KEY
  only:
    - develop

deploy-backend:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd backend
    - dpl --provider=heroku --app=$HEROKU_BACKEND --api-key=$HEROKU_API_KEY
  only:
    - develop
